# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(668, 411)
        Form.setStyleSheet("* {\n"
"    background-color: 0;\n"
"    border: 0;\n"
"    border-radius: 0;\n"
"}\n"
"*:hover {\n"
"    background-color: 0;\n"
"    border: 0;\n"
"    border-radius: 0;\n"
"}")
        self.signup = QtWidgets.QPushButton(Form)
        self.signup.setGeometry(QtCore.QRect(265, 260, 141, 31))
        self.signup.setStyleSheet("* {\n"
"color: white;\n"
"background-color: #2d3035;\n"
"border: 2px solid #878787;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"*:hover {\n"
"border: 2px solid #DBDBDB;\n"
"}\n"
"\n"
"*:focus {\n"
"border-color: green;\n"
"border-color: red;\n"
"}\n"
"")
        self.signup.setObjectName("signup")
        self.login = QtWidgets.QLineEdit(Form)
        self.login.setGeometry(QtCore.QRect(235, 100, 201, 41))
        self.login.setStyleSheet("* {\n"
"color: white;\n"
"background-color: #2d3035;\n"
"border: 2px solid #878787;\n"
"border-bottom: 2px solid red;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"*:hover {\n"
"border-color: #DBDBDB;\n"
"}\n"
"\n"
"*:focus {\n"
"background-color: #181C20;\n"
"border-color: #fd413c;\n"
"}")
        self.login.setMaxLength(15)
        self.login.setPlaceholderText("")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(235, 180, 201, 41))
        self.password.setStyleSheet("* {\n"
"color: white;\n"
"background-color: #2d3035;\n"
"border: 2px solid #878787;\n"
"border-bottom: 2px solid red;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"*:hover {\n"
"border-color: #DBDBDB;\n"
"}\n"
"\n"
"*:focus {\n"
"background-color: #181C20;\n"
"border-color: #fd413c;\n"
"}")
        self.password.setMaxLength(15)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(610, 20, 21, 21))
        self.closeButton.setStyleSheet("* {\n"
"background-image: url(:/close/image/close.png);\n"
"}\n"
"\n"
"*:hover {\n"
"background-image: url(:/close/image/close-red.png);\n"
"}")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.hideButton = QtWidgets.QPushButton(Form)
        self.hideButton.setGeometry(QtCore.QRect(580, 21, 21, 21))
        self.hideButton.setStyleSheet("* {\n"
"background-image: url(:/hide/image/hide.png);\n"
"}\n"
"\n"
"*:hover {\n"
"background-image: url(:/hide/image/hide-gray.png);\n"
"}")
        self.hideButton.setText("")
        self.hideButton.setObjectName("hideButton")
        self.loginlabel = QtWidgets.QLabel(Form)
        self.loginlabel.setGeometry(QtCore.QRect(240, 70, 71, 30))
        self.loginlabel.setStyleSheet("color: white;\n"
"font: 8pt \"Montserrat\";")
        self.loginlabel.setObjectName("loginlabel")
        self.passwordlabel = QtWidgets.QLabel(Form)
        self.passwordlabel.setGeometry(QtCore.QRect(240, 150, 71, 30))
        self.passwordlabel.setStyleSheet("color: white;\n"
"font: 8pt \"Montserrat\";")
        self.passwordlabel.setObjectName("passwordlabel")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 651, 391))
        self.frame.setStyleSheet("background-color: #212529;\n"
"border-radius: 20px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.login.raise_()
        self.signup.raise_()
        self.password.raise_()
        self.closeButton.raise_()
        self.hideButton.raise_()
        self.loginlabel.raise_()
        self.passwordlabel.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.signup.setText(_translate("Form", "Войти"))
        self.loginlabel.setText(_translate("Form", "Логин"))
        self.passwordlabel.setText(_translate("Form", "Пароль"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
